version: '3'
services:
    ticketsystem8080:
        container_name: "ticketsystem"
        image: "registry.guoduhao.cn:9000/ticketsystem"
        ports:
         - "8080:8080"
        restart: always
    ticketsystem8081:
        container_name: "ticketsystem"
        image: "registry.guoduhao.cn:9000/ticketsystem"
        ports:
         - "8081:8080"
        restart: always
